import type { CelestialBodyData, CelestialBodyId, CelestialBodyKind } from './types';

export const CELESTIAL_BODIES: CelestialBodyData[] = [
  {
    id: 'sun',
    parentId: null,
    name: 'Солнце',
    kind: 'star',
    shape: 'sphere',
    color: '#ffb44a',
    textureFile: 'sun.jpg',
    radius: 2.7,
    orbitRadius: 0,
    eccentricity: 0,
    perihelionAngle: 0,
    orbitalPeriodDays: 0,
    orbitDirection: 'prograde',
    rotationPeriodDays: 25.38,
    rotationDirection: 'prograde',
    axialTiltDegrees: 7.25,
    isTidallyLocked: false,
    initialAngle: 0,
    distanceLabel: 'Центр системы',
    orbitalPeriodLabel: 'Не применимо',
    rotationPeriodLabel: 'Около 25 суток на экваторе',
    description: 'Звезда, вокруг которой обращаются все объекты системы.',
  },
  {
    id: 'mercury',
    parentId: 'sun',
    name: 'Меркурий',
    kind: 'planet',
    shape: 'sphere',
    color: '#9b948b',
    textureFile: 'mercury.jpg',
    radius: 0.42,
    orbitRadius: 4.8,
    eccentricity: 0.20563593,
    perihelionAngle: (77.45779628 * Math.PI) / 180,
    orbitalPeriodDays: 87.97,
    orbitDirection: 'prograde',
    rotationPeriodDays: 58.646,
    rotationDirection: 'prograde',
    axialTiltDegrees: 0.034,
    isTidallyLocked: false,
    initialAngle: 0.45,
    distanceLabel: '57,9 млн км от Солнца',
    orbitalPeriodLabel: '88 земных суток',
    rotationPeriodLabel: '58,6 земных суток',
    description: 'Ближайшая к Солнцу и самая маленькая планета Солнечной системы.',
  },
  {
    atmosphere: {
      color: '#e9c878',
      opacity: 0.13,
      scale: 1.055,
    },
    id: 'venus',
    parentId: 'sun',
    name: 'Венера',
    kind: 'planet',
    shape: 'sphere',
    color: '#e8bd75',
    textureFile: 'venus.jpg',
    radius: 0.72,
    orbitRadius: 7.5,
    eccentricity: 0.00677672,
    perihelionAngle: (131.60246718 * Math.PI) / 180,
    orbitalPeriodDays: 224.7,
    orbitDirection: 'prograde',
    rotationPeriodDays: 243.025,
    rotationDirection: 'retrograde',
    axialTiltDegrees: 2.64,
    isTidallyLocked: false,
    initialAngle: 1.7,
    distanceLabel: '108,2 млн км от Солнца',
    orbitalPeriodLabel: '224,7 земных суток',
    rotationPeriodLabel: '243 суток, ретроградно',
    description: 'Самая горячая планета системы с плотной облачной атмосферой.',
  },
  {
    atmosphere: {
      color: '#70c8ff',
      opacity: 0.18,
      scale: 1.045,
    },
    id: 'earth',
    parentId: 'sun',
    name: 'Земля',
    kind: 'planet',
    shape: 'sphere',
    color: '#4c86c6',
    textureFile: 'earth.jpg',
    radius: 0.8,
    orbitRadius: 11,
    eccentricity: 0.01671123,
    perihelionAngle: (102.93768193 * Math.PI) / 180,
    orbitalPeriodDays: 365.25,
    orbitDirection: 'prograde',
    rotationPeriodDays: 0.99726968,
    rotationDirection: 'prograde',
    axialTiltDegrees: 23.44,
    isTidallyLocked: false,
    initialAngle: 3.1,
    distanceLabel: '149,6 млн км от Солнца',
    orbitalPeriodLabel: '365,25 суток',
    rotationPeriodLabel: '23 ч 56 мин',
    description:
      'Планета с жидкой водой, кислородной атмосферой и единственным естественным спутником.',
  },
  {
    id: 'moon',
    parentId: 'earth',
    name: 'Луна',
    kind: 'satellite',
    shape: 'sphere',
    color: '#b9bcc4',
    textureFile: 'moon.jpg',
    radius: 0.18,
    orbitRadius: 1.65,
    eccentricity: 0.0549,
    perihelionAngle: 0,
    orbitalPeriodDays: 27.321661,
    orbitDirection: 'prograde',
    rotationPeriodDays: 27.321661,
    rotationDirection: 'prograde',
    axialTiltDegrees: 6.68,
    isTidallyLocked: true,
    initialAngle: 0.4,
    distanceLabel: '384 400 км от Земли',
    orbitalPeriodLabel: '27,3 земных суток',
    rotationPeriodLabel: '27,3 суток, синхронно',
    description:
      'Единственный естественный спутник Земли, влияющий на приливы и стабилизирующий наклон её оси.',
  },
  {
    atmosphere: {
      color: '#ce7656',
      opacity: 0.075,
      scale: 1.025,
    },
    id: 'mars',
    parentId: 'sun',
    name: 'Марс',
    kind: 'planet',
    shape: 'sphere',
    color: '#b95835',
    textureFile: 'mars.jpg',
    radius: 0.62,
    orbitRadius: 15,
    eccentricity: 0.0933941,
    perihelionAngle: (-23.94362959 * Math.PI) / 180,
    orbitalPeriodDays: 687,
    orbitDirection: 'prograde',
    rotationPeriodDays: 1.02595675,
    rotationDirection: 'prograde',
    axialTiltDegrees: 25.19,
    isTidallyLocked: false,
    initialAngle: 5.2,
    distanceLabel: '227,9 млн км от Солнца',
    orbitalPeriodLabel: '687 земных суток',
    rotationPeriodLabel: '24 ч 37 мин',
    description: 'Холодная пустынная планета с крупнейшим вулканом Солнечной системы.',
  },
  {
    id: 'phobos',
    parentId: 'mars',
    name: 'Фобос',
    kind: 'satellite',
    shape: 'irregular',
    color: '#9d8f7d',
    radius: 0.1,
    orbitRadius: 1.25,
    eccentricity: 0.0151,
    perihelionAngle: 0,
    orbitalPeriodDays: 0.31891,
    orbitDirection: 'prograde',
    rotationPeriodDays: 0.31891,
    rotationDirection: 'prograde',
    axialTiltDegrees: 0,
    isTidallyLocked: true,
    initialAngle: 1.2,
    distanceLabel: '9 376 км от центра Марса',
    orbitalPeriodLabel: '7 ч 39 мин',
    rotationPeriodLabel: '7 ч 39 мин, синхронно',
    description:
      'Крупнейший спутник Марса неправильной формы, постепенно приближающийся к планете.',
  },
  {
    id: 'deimos',
    parentId: 'mars',
    name: 'Деймос',
    kind: 'satellite',
    shape: 'irregular',
    color: '#b0a28c',
    radius: 0.08,
    orbitRadius: 1.85,
    eccentricity: 0.0002,
    perihelionAngle: 0,
    orbitalPeriodDays: 1.26244,
    orbitDirection: 'prograde',
    rotationPeriodDays: 1.26244,
    rotationDirection: 'prograde',
    axialTiltDegrees: 0,
    isTidallyLocked: true,
    initialAngle: 4.1,
    distanceLabel: '23 463 км от центра Марса',
    orbitalPeriodLabel: '30 ч 18 мин',
    rotationPeriodLabel: '30 ч 18 мин, синхронно',
    description: 'Меньший и более удалённый спутник Марса с тёмной кратерированной поверхностью.',
  },
];

export function getCelestialBodyById(id?: CelestialBodyId): CelestialBodyData | undefined {
  return id ? CELESTIAL_BODIES.find((body) => body.id === id) : undefined;
}

export function getChildBodies(parentId: CelestialBodyId): CelestialBodyData[] {
  return CELESTIAL_BODIES.filter((body) => body.parentId === parentId);
}

export function getBodiesByKind(kind: CelestialBodyKind): CelestialBodyData[] {
  return CELESTIAL_BODIES.filter((body) => body.kind === kind);
}
