import type { CelestialBodyData, CelestialBodyId, CelestialBodyKind } from './types';

export const CELESTIAL_BODIES: CelestialBodyData[] = [
  {
    id: 'sun',
    parentId: null,
    name: 'Солнце',
    kind: 'star',
    shape: 'sphere',
    color: '#ffb44a',
    textureFile: 'sun.jpg',
    radius: 2.7,
    orbitRadius: 0,
    eccentricity: 0,
    perihelionAngle: 0,
    orbitalPeriodDays: 0,
    orbitDirection: 'prograde',
    rotationPeriodDays: 25.38,
    rotationDirection: 'prograde',
    axialTiltDegrees: 7.25,
    isTidallyLocked: false,
    initialAngle: 0,
    distanceLabel: 'Центр системы',
    orbitalPeriodLabel: 'Не применимо',
    rotationPeriodLabel: 'Около 25 суток на экваторе',
    description: 'Звезда, вокруг которой обращаются все объекты системы.',
  },
  {
    id: 'mercury',
    parentId: 'sun',
    name: 'Меркурий',
    kind: 'planet',
    shape: 'sphere',
    color: '#9b948b',
    textureFile: 'mercury.jpg',
    radius: 0.42,
    orbitRadius: 4.8,
    eccentricity: 0.20563593,
    perihelionAngle: (77.45779628 * Math.PI) / 180,
    orbitalPeriodDays: 87.97,
    orbitDirection: 'prograde',
    rotationPeriodDays: 58.646,
    rotationDirection: 'prograde',
    axialTiltDegrees: 0.034,
    isTidallyLocked: false,
    initialAngle: 0.45,
    distanceLabel: '57,9 млн км от Солнца',
    orbitalPeriodLabel: '88 земных суток',
    rotationPeriodLabel: '58,6 земных суток',
    description: 'Ближайшая к Солнцу и самая маленькая планета Солнечной системы.',
  },
  {
    atmosphere: {
      color: '#e9c878',
      opacity: 0.13,
      scale: 1.055,
    },
    id: 'venus',
    parentId: 'sun',
    name: 'Венера',
    kind: 'planet',
    shape: 'sphere',
    color: '#e8bd75',
    textureFile: 'venus.jpg',
    radius: 0.72,
    orbitRadius: 7.5,
    eccentricity: 0.00677672,
    perihelionAngle: (131.60246718 * Math.PI) / 180,
    orbitalPeriodDays: 224.7,
    orbitDirection: 'prograde',
    rotationPeriodDays: 243.025,
    rotationDirection: 'retrograde',
    axialTiltDegrees: 2.64,
    isTidallyLocked: false,
    initialAngle: 1.7,
    distanceLabel: '108,2 млн км от Солнца',
    orbitalPeriodLabel: '224,7 земных суток',
    rotationPeriodLabel: '243 суток, ретроградно',
    description: 'Самая горячая планета системы с плотной облачной атмосферой.',
  },
  {
    atmosphere: {
      color: '#70c8ff',
      opacity: 0.18,
      scale: 1.045,
    },
    id: 'earth',
    parentId: 'sun',
    name: 'Земля',
    kind: 'planet',
    shape: 'sphere',
    color: '#4c86c6',
    textureFile: 'earth.jpg',
    radius: 0.8,
    orbitRadius: 11,
    eccentricity: 0.01671123,
    perihelionAngle: (102.93768193 * Math.PI) / 180,
    orbitalPeriodDays: 365.25,
    orbitDirection: 'prograde',
    rotationPeriodDays: 0.99726968,
    rotationDirection: 'prograde',
    axialTiltDegrees: 23.44,
    isTidallyLocked: false,
    initialAngle: 3.1,
    distanceLabel: '149,6 млн км от Солнца',
    orbitalPeriodLabel: '365,25 суток',
    rotationPeriodLabel: '23 ч 56 мин',
    description:
      'Планета с жидкой водой, кислородной атмосферой и единственным естественным спутником.',
  },
  {
    id: 'moon',
    parentId: 'earth',
    name: 'Луна',
    kind: 'satellite',
    shape: 'sphere',
    color: '#b9bcc4',
    textureFile: 'moon.jpg',
    radius: 0.18,
    orbitRadius: 1.65,
    eccentricity: 0.0549,
    perihelionAngle: 0,
    orbitalPeriodDays: 27.321661,
    orbitDirection: 'prograde',
    rotationPeriodDays: 27.321661,
    rotationDirection: 'prograde',
    axialTiltDegrees: 6.68,
    isTidallyLocked: true,
    initialAngle: 0.4,
    distanceLabel: '384 400 км от Земли',
    orbitalPeriodLabel: '27,3 земных суток',
    rotationPeriodLabel: '27,3 суток, синхронно',
    description:
      'Единственный естественный спутник Земли, влияющий на приливы и стабилизирующий наклон её оси.',
  },
  {
    atmosphere: {
      color: '#ce7656',
      opacity: 0.075,
      scale: 1.025,
    },
    id: 'mars',
    parentId: 'sun',
    name: 'Марс',
    kind: 'planet',
    shape: 'sphere',
    color: '#b95835',
    textureFile: 'mars.jpg',
    radius: 0.62,
    orbitRadius: 15,
    eccentricity: 0.0933941,
    perihelionAngle: (-23.94362959 * Math.PI) / 180,
    orbitalPeriodDays: 687,
    orbitDirection: 'prograde',
    rotationPeriodDays: 1.02595675,
    rotationDirection: 'prograde',
    axialTiltDegrees: 25.19,
    isTidallyLocked: false,
    initialAngle: 5.2,
    distanceLabel: '227,9 млн км от Солнца',
    orbitalPeriodLabel: '687 земных суток',
    rotationPeriodLabel: '24 ч 37 мин',
    description: 'Холодная пустынная планета с крупнейшим вулканом Солнечной системы.',
  },
  {
    id: 'phobos',
    parentId: 'mars',
    name: 'Фобос',
    kind: 'satellite',
    shape: 'irregular',
    color: '#9d8f7d',
    radius: 0.1,
    orbitRadius: 1.25,
    eccentricity: 0.0151,
    perihelionAngle: 0,
    orbitalPeriodDays: 0.31891,
    orbitDirection: 'prograde',
    rotationPeriodDays: 0.31891,
    rotationDirection: 'prograde',
    axialTiltDegrees: 0,
    isTidallyLocked: true,
    initialAngle: 1.2,
    distanceLabel: '9 376 км от центра Марса',
    orbitalPeriodLabel: '7 ч 39 мин',
    rotationPeriodLabel: '7 ч 39 мин, синхронно',
    description:
      'Крупнейший спутник Марса неправильной формы, постепенно приближающийся к планете.',
  },
  {
    id: 'deimos',
    parentId: 'mars',
    name: 'Деймос',
    kind: 'satellite',
    shape: 'irregular',
    color: '#b0a28c',
    radius: 0.08,
    orbitRadius: 1.85,
    eccentricity: 0.0002,
    perihelionAngle: 0,
    orbitalPeriodDays: 1.26244,
    orbitDirection: 'prograde',
    rotationPeriodDays: 1.26244,
    rotationDirection: 'prograde',
    axialTiltDegrees: 0,
    isTidallyLocked: true,
    initialAngle: 4.1,
    distanceLabel: '23 463 км от центра Марса',
    orbitalPeriodLabel: '30 ч 18 мин',
    rotationPeriodLabel: '30 ч 18 мин, синхронно',
    description: 'Меньший и более удалённый спутник Марса с тёмной кратерированной поверхностью.',
  },
  {
    atmosphere: {
      color: '#d8b58a',
      opacity: 0.08,
      scale: 1.025,
    },
    id: 'jupiter',
    parentId: 'sun',
    name: 'Юпитер',
    kind: 'planet',
    shape: 'sphere',
    color: '#d0a477',
    radius: 1.55,
    orbitRadius: 20.5,
    eccentricity: 0.0489,
    perihelionAngle: (14.75 * Math.PI) / 180,
    orbitalPeriodDays: 4332.59,
    orbitDirection: 'prograde',
    rotationPeriodDays: 0.41354,
    rotationDirection: 'prograde',
    axialTiltDegrees: 3.13,
    isTidallyLocked: false,
    initialAngle: 2.35,
    distanceLabel: '778,5 млн км от Солнца',
    orbitalPeriodLabel: '11,86 земного года',
    rotationPeriodLabel: '9 ч 56 мин',
    description:
      'Крупнейшая планета Солнечной системы, газовый гигант с мощными штормами и Большим красным пятном.',
  },
  {
    id: 'io',
    parentId: 'jupiter',
    name: 'Ио',
    kind: 'satellite',
    shape: 'sphere',
    color: '#d9b54a',
    radius: 0.23,
    orbitRadius: 2.35,
    eccentricity: 0.0041,
    perihelionAngle: 0,
    orbitalPeriodDays: 1.769,
    orbitDirection: 'prograde',
    rotationPeriodDays: 1.769,
    rotationDirection: 'prograde',
    axialTiltDegrees: 0.05,
    isTidallyLocked: true,
    initialAngle: 0.35,
    distanceLabel: '421 700 км от Юпитера',
    orbitalPeriodLabel: '1,77 земных суток',
    rotationPeriodLabel: '1,77 суток, синхронно',
    description:
      'Самый вулканически активный объект Солнечной системы, поверхность которого постоянно обновляется.',
  },
  {
    id: 'europa',
    parentId: 'jupiter',
    name: 'Европа',
    kind: 'satellite',
    shape: 'sphere',
    color: '#cbbd9b',
    radius: 0.2,
    orbitRadius: 3,
    eccentricity: 0.0094,
    perihelionAngle: 0,
    orbitalPeriodDays: 3.551,
    orbitDirection: 'prograde',
    rotationPeriodDays: 3.551,
    rotationDirection: 'prograde',
    axialTiltDegrees: 0.1,
    isTidallyLocked: true,
    initialAngle: 2.1,
    distanceLabel: '670 900 км от Юпитера',
    orbitalPeriodLabel: '3,55 земных суток',
    rotationPeriodLabel: '3,55 суток, синхронно',
    description: 'Ледяной спутник с вероятным глобальным океаном жидкой воды под поверхностью.',
  },
  {
    id: 'ganymede',
    parentId: 'jupiter',
    name: 'Ганимед',
    kind: 'satellite',
    shape: 'sphere',
    color: '#938779',
    radius: 0.3,
    orbitRadius: 3.85,
    eccentricity: 0.0013,
    perihelionAngle: 0,
    orbitalPeriodDays: 7.155,
    orbitDirection: 'prograde',
    rotationPeriodDays: 7.155,
    rotationDirection: 'prograde',
    axialTiltDegrees: 0.2,
    isTidallyLocked: true,
    initialAngle: 4.2,
    distanceLabel: '1 070 400 км от Юпитера',
    orbitalPeriodLabel: '7,15 земных суток',
    rotationPeriodLabel: '7,15 суток, синхронно',
    description:
      'Крупнейший спутник Солнечной системы и единственная известная луна с собственным магнитным полем.',
  },
  {
    id: 'callisto',
    parentId: 'jupiter',
    name: 'Каллисто',
    kind: 'satellite',
    shape: 'sphere',
    color: '#6f655c',
    radius: 0.28,
    orbitRadius: 4.75,
    eccentricity: 0.0074,
    perihelionAngle: 0,
    orbitalPeriodDays: 16.689,
    orbitDirection: 'prograde',
    rotationPeriodDays: 16.689,
    rotationDirection: 'prograde',
    axialTiltDegrees: 0.4,
    isTidallyLocked: true,
    initialAngle: 5.5,
    distanceLabel: '1 882 700 км от Юпитера',
    orbitalPeriodLabel: '16,69 земных суток',
    rotationPeriodLabel: '16,69 суток, синхронно',
    description:
      'Древний ледяной мир с одной из самых сильно кратерированных поверхностей в системе.',
  },
  {
    atmosphere: {
      color: '#e6cf9e',
      opacity: 0.07,
      scale: 1.025,
    },
    rings: {
      color: '#c8ad82',
      innerRadius: 1.45,
      outerRadius: 2.45,
      opacity: 0.78,
    },
    id: 'saturn',
    parentId: 'sun',
    name: 'Сатурн',
    kind: 'planet',
    shape: 'sphere',
    color: '#d8bd86',
    radius: 1.35,
    orbitRadius: 27,
    eccentricity: 0.0565,
    perihelionAngle: (92.43 * Math.PI) / 180,
    orbitalPeriodDays: 10759.22,
    orbitDirection: 'prograde',
    rotationPeriodDays: 0.444,
    rotationDirection: 'prograde',
    axialTiltDegrees: 26.73,
    isTidallyLocked: false,
    initialAngle: 4.85,
    distanceLabel: '1,43 млрд км от Солнца',
    orbitalPeriodLabel: '29,45 земного года',
    rotationPeriodLabel: 'Около 10 ч 42 мин',
    description:
      'Газовый гигант с самой заметной системой колец, состоящей преимущественно из частиц водяного льда.',
  },
  {
    atmosphere: {
      color: '#d7ad68',
      opacity: 0.12,
      scale: 1.055,
    },
    id: 'titan',
    parentId: 'saturn',
    name: 'Титан',
    kind: 'satellite',
    shape: 'sphere',
    color: '#c8924d',
    radius: 0.3,
    orbitRadius: 3.45,
    eccentricity: 0.0288,
    perihelionAngle: 0,
    orbitalPeriodDays: 15.945,
    orbitDirection: 'prograde',
    rotationPeriodDays: 15.945,
    rotationDirection: 'prograde',
    axialTiltDegrees: 0.3,
    isTidallyLocked: true,
    initialAngle: 1.25,
    distanceLabel: '1 221 870 км от Сатурна',
    orbitalPeriodLabel: '15,95 земных суток',
    rotationPeriodLabel: '15,95 суток, синхронно',
    description:
      'Крупнейший спутник Сатурна с плотной азотной атмосферой, метановыми облаками, реками и озёрами.',
  },
];

export function getCelestialBodyById(id?: CelestialBodyId): CelestialBodyData | undefined {
  return id ? CELESTIAL_BODIES.find((body) => body.id === id) : undefined;
}

export function getChildBodies(parentId: CelestialBodyId): CelestialBodyData[] {
  return CELESTIAL_BODIES.filter((body) => body.parentId === parentId);
}

export function getBodiesByKind(kind: CelestialBodyKind): CelestialBodyData[] {
  return CELESTIAL_BODIES.filter((body) => body.kind === kind);
}
