import type { CelestialBodyData } from './types';

export const CELESTIAL_BODIES: CelestialBodyData[] = [
  {
    id: 'sun',
    name: 'Солнце',
    type: 'star',
    color: '#ffb44a',
    textureFile: 'sun.jpg',
    radius: 2.7,
    orbitRadius: 0,
    eccentricity: 0,
    perihelionAngle: 0,
    orbitalPeriodDays: 0,
    initialAngle: 0,
    distanceLabel: 'Центр системы',
    orbitalPeriodLabel: 'Не применимо',
    description: 'Звезда, вокруг которой обращаются все объекты системы.',
    satellites: [],
  },
  {
    id: 'mercury',
    name: 'Меркурий',
    type: 'planet',
    color: '#9b948b',
    textureFile: 'mercury.jpg',
    radius: 0.42,
    orbitRadius: 4.8,
    eccentricity: 0.20563593,
    perihelionAngle: (77.45779628 * Math.PI) / 180,
    orbitalPeriodDays: 87.97,
    initialAngle: 0.45,
    distanceLabel: '57,9 млн км от Солнца',
    orbitalPeriodLabel: '88 земных суток',
    description: 'Ближайшая к Солнцу и самая маленькая планета Солнечной системы.',
    satellites: [],
  },
  {
    atmosphere: {
      color: '#e9c878',
      opacity: 0.13,
      scale: 1.055,
    },
    id: 'venus',
    name: 'Венера',
    type: 'planet',
    color: '#e8bd75',
    textureFile: 'venus.jpg',
    radius: 0.72,
    orbitRadius: 7.5,
    eccentricity: 0.00677672,
    perihelionAngle: (131.60246718 * Math.PI) / 180,
    orbitalPeriodDays: 224.7,
    initialAngle: 1.7,
    distanceLabel: '108,2 млн км от Солнца',
    orbitalPeriodLabel: '224,7 земных суток',
    description: 'Самая горячая планета системы с плотной облачной атмосферой.',
    satellites: [],
  },
  {
    atmosphere: {
      color: '#70c8ff',
      opacity: 0.18,
      scale: 1.045,
    },
    id: 'earth',
    name: 'Земля',
    type: 'planet',
    color: '#4c86c6',
    textureFile: 'earth.jpg',
    radius: 0.8,
    orbitRadius: 11,
    eccentricity: 0.01671123,
    perihelionAngle: (102.93768193 * Math.PI) / 180,
    orbitalPeriodDays: 365.25,
    initialAngle: 3.1,
    distanceLabel: '149,6 млн км от Солнца',
    orbitalPeriodLabel: '365,25 суток',
    description:
      'Планета с жидкой водой, кислородной атмосферой и единственным естественным спутником.',
    satellites: [
      {
        id: 'moon',
        name: 'Луна',
        color: '#b9bcc4',
        textureFile: 'moon.jpg',
        radius: 0.18,
        orbitRadius: 1.65,
        orbitalSpeed: 0.9,
        initialAngle: 0.4,
      },
    ],
  },
  {
    atmosphere: {
      color: '#ce7656',
      opacity: 0.075,
      scale: 1.025,
    },
    id: 'mars',
    name: 'Марс',
    type: 'planet',
    color: '#b95835',
    textureFile: 'mars.jpg',
    radius: 0.62,
    orbitRadius: 15,
    eccentricity: 0.0933941,
    perihelionAngle: (-23.94362959 * Math.PI) / 180,
    orbitalPeriodDays: 687,
    initialAngle: 5.2,
    distanceLabel: '227,9 млн км от Солнца',
    orbitalPeriodLabel: '687 земных суток',
    description: 'Холодная пустынная планета с крупнейшим вулканом Солнечной системы.',
    satellites: [
      {
        id: 'phobos',
        name: 'Фобос',
        color: '#9d8f7d',
        radius: 0.1,
        orbitRadius: 1.25,
        orbitalSpeed: 1.45,
        initialAngle: 1.2,
      },
      {
        id: 'deimos',
        name: 'Деймос',
        color: '#b0a28c',
        radius: 0.08,
        orbitRadius: 1.85,
        orbitalSpeed: 0.72,
        initialAngle: 4.1,
      },
    ],
  },
];
